const renderArr = (cate, group) =>
  [`${cate}-${group}-01`, `${cate}-${group}-02`, `${cate}-${group}-03`, `${cate}-${group}-04`, `${cate}-${group}-05`]

export default {
  A: {
    a: renderArr('A', 'a'),
    b: renderArr('A', 'b'),
    c: renderArr('A', 'c'),
    d: renderArr('A', 'd'),
    e: renderArr('A', 'e'),
    f: renderArr('A', 'f'),
    g: renderArr('A', 'g'),
    h: renderArr('A', 'h'),
  },
  B: {
    a: renderArr('B', 'a'),
    b: renderArr('B', 'b'),
    c: renderArr('B', 'c'),
    d: renderArr('B', 'd'),
    e: renderArr('B', 'e'),
    f: renderArr('B', 'f'),
    g: renderArr('B', 'g'),
    h: renderArr('B', 'h'),
  },
  C: {
    a: renderArr('C', 'a'),
    b: renderArr('C', 'b'),
    c: renderArr('C', 'c'),
    d: renderArr('C', 'd'),
    e: renderArr('C', 'e'),
    f: renderArr('C', 'f'),
    g: renderArr('C', 'g'),
    h: renderArr('C', 'h'),
  },
  D: {
    a: renderArr('D', 'a'),
    b: renderArr('D', 'b'),
    c: renderArr('D', 'c'),
    d: renderArr('D', 'd'),
    e: renderArr('D', 'e'),
    f: renderArr('D', 'f'),
    g: renderArr('D', 'g'),
    h: renderArr('D', 'h'),
  },
  E: {
    a: renderArr('E', 'a'),
    b: renderArr('E', 'b'),
    c: renderArr('E', 'c'),
    d: renderArr('E', 'd'),
    e: renderArr('E', 'e'),
    f: renderArr('E', 'f'),
    g: renderArr('E', 'g'),
    h: renderArr('E', 'h'),
  },
  F: {
    a: renderArr('F', 'a'),
    b: renderArr('F', 'b'),
    c: renderArr('F', 'c'),
    d: renderArr('F', 'd'),
    e: renderArr('F', 'e'),
    f: renderArr('F', 'f'),
    g: renderArr('F', 'g'),
    h: renderArr('F', 'h'),
  },
};