const renderArr = (cate, group) =>
  [`${cate}-${group}-01`, `${cate}-${group}-02`, `${cate}-${group}-03`, `${cate}-${group}-04`, `${cate}-${group}-05`]

export default {
  A: {
    Aa: renderArr('A', 'Aa'),
    Ab: renderArr('A', 'Ab'),
    Ac: renderArr('A', 'Ac'),
    Ad: renderArr('A', 'Ad'),
    Ae: renderArr('A', 'Ae'),
    Af: renderArr('A', 'Af'),
    Ag: renderArr('A', 'Ag'),
    Ah: renderArr('A', 'Ah'),
  },
  B: {
    Ba: renderArr('B', 'Ba'),
    Bb: renderArr('B', 'Bb'),
    Bc: renderArr('B', 'Bc'),
    Bd: renderArr('B', 'Bd'),
    Be: renderArr('B', 'Be'),
    Bf: renderArr('B', 'Bf'),
    Bg: renderArr('B', 'Bg'),
    Bh: renderArr('B', 'Bh'),
  },
  C: {
    Ca: renderArr('C', 'Ca'),
    Cb: renderArr('C', 'Cb'),
    Cc: renderArr('C', 'Cc'),
    Cd: renderArr('C', 'Cd'),
    Ce: renderArr('C', 'Ce'),
    Cf: renderArr('C', 'Cf'),
    Cg: renderArr('C', 'Cg'),
    Ch: renderArr('C', 'Ch'),
  },
  D: {
    Da: renderArr('D', 'Da'),
    Db: renderArr('D', 'Db'),
    Dc: renderArr('D', 'Dc'),
    Dd: renderArr('D', 'Dd'),
    De: renderArr('D', 'De'),
    Df: renderArr('D', 'Df'),
    Dg: renderArr('D', 'Dg'),
    Dh: renderArr('D', 'Dh'),
  },
  E: {
    Ea: renderArr('E', 'Ea'),
    Eb: renderArr('E', 'Eb'),
    Ec: renderArr('E', 'Ec'),
    Ed: renderArr('E', 'Ed'),
    Ee: renderArr('E', 'Ee'),
    Ef: renderArr('E', 'Ef'),
    Eg: renderArr('E', 'Eg'),
    Eh: renderArr('E', 'Eh'),
  },
  F: {
    Fa: renderArr('F', 'Fa'),
    Fb: renderArr('F', 'Fb'),
    Fc: renderArr('F', 'Fc'),
    Fd: renderArr('F', 'Fd'),
    Fe: renderArr('F', 'Fe'),
    Ff: renderArr('F', 'Ff'),
    Fg: renderArr('F', 'Fg'),
    Fh: renderArr('F', 'Fh'),
  },
};